apiVersion: apps/v1
kind: Deployment
metadata:
  name: javatomcat
  labels:
    app: javatomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javatomcat
  template:
    metadata:
      labels:
        app: javatomcat
    spec:
      containers:
      - name: javaapp
        image: deepthidocker0704/javatomcat
        ports:
        - containerPort: 5000
