apiVersion: v1
kind: Service
metadata:
  labels:
    app: javaapp
  name: javaapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 9000
      protocol: TCP
  selector:
    app: javaapp
