apiVersion: v1
kind: Service
metadata:
  labels:
    app: javatomcat
  name: javatomcat
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 5000
      protocol: TCP
  selector:
    app: javatomcat
